### ISSUE TITLE
[ask] model h5

### ISSUE THREAD

**Issue by isnuryusuf** [jxwleong/coral-sleuth#23]
Hi

can you share file or inform me to generate: 

coral_reef_classifier_efficientnetv2_full_epoch_200_1_batchsize_32_combined_annotations_about_40k_png_only_remapped_majority_class_with_3k_to_4k_sample_reduced_1k_scale_0.2.h5

thank

**Comment by jxwleong** [comment]
Hi @isnuryusuf, 

Did you manage to download the full datasets?

You can train the model to generate this file (`coral_reef_classifier_efficientnetv2_full_epoch_200_1_batchsize_32_combined_annotations_about_40k_png_only_remapped_majority_class_with_3k_to_4k_sample_reduced_1k_scale_0.2.h5`)

or do you mind to share me your email? I can give you access to this file on my Google Drive.

Regards,
Jason

**Comment by isnuryusuf** [comment]
thnks @jxwleong

**Comment by jxwleong** [comment]
I have shared the file with your Gmail. Have to look and let me know if you need any other information.

**Comment by isnuryusuf** [comment]
thnks @jxwleong

but i think iam not received your file

**Comment by jxwleong** [comment]
My bad!

Looks like my organization's Google Drive is preventing it to shared with others outside of the organization and I can't upload it to my personal drive or email it to you directly due to its size.

Would you want to try to train the model and generate the file on your own? I can share the steps later if you're interested.

**Comment by isnuryusuf** [comment]
Yes sure, thnks

**Comment by isnuryusuf** [comment]
terima kasih

**Comment by jxwleong** [comment]
Alright.

Here are the steps (assuming the datasets are downloaded and placed in `/data/images`):
1. Change the following variables to the desired settings. Such as `combined_annotations_about_40k_png_only_remapped_majority_class_with_3k_to_4k_sample_reduced_1k.csv` and `0.2`. https://github.com/jxwleong/coral-sleuth/blob/c62dddee3e23e34aa13838a9c52dbdbf66dca0c9/src/model_training.py#L167
https://github.com/jxwleong/coral-sleuth/blob/c62dddee3e23e34aa13838a9c52dbdbf66dca0c9/src/model_training.py#L191

3. Execute the `/src/model_training.py`.


I'm running the model training on a dedicated server.
